### ISSUE TITLE
Latest version has dependency error

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#107]
When upgrading, with this commit a6c96e2dc6e935ae9fdc3daa278b57daa30ba43:

    git pull origin master
    docker-compose down
    docker-compose up -d

Docker versions:

    docker-compose 1.13.0
    docker 17.03.01-ce

Error:

```
Traceback (most recent call last):
  File "/srv/app/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/srv/env/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/env/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/srv/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
```

**Comment by jkp85** [comment]
Resolved
