### ISSUE TITLE
Cannot Start RStudio Image

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#483]
#482 After the changes for #447, users still cannot start a server. The following error message is produced by the `deployment_celery_1` container:
```
[2017-10-31 13:59:14,918: ERROR/ForkPoolWorker-2] Task servers.tasks.start_server[a5111a75-0ce4-4e09-aea2-65846fef2006] raised unexpected: JSONDecodeError('Expecting value: line 2 column 1 (char 1)',)
Traceback (most recent call last):
  File "/srv/env/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/env/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/app/servers/tasks.py", line 14, in start_server
    server_action('start', server)
  File "/srv/app/servers/tasks.py", line 9, in server_action
    getattr(spawner, action)()
  File "/srv/app/servers/spawners.py", line 77, in start
    self._create_container()
  File "/srv/app/servers/spawners.py", line 145, in _create_container
    docker_resp = self.client.api.create_container(**self._create_container_config())
  File "/srv/app/servers/spawners.py", line 161, in _create_container_config
    if self._is_gpu_instance:
  File "/srv/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/app/servers/spawners.py", line 354, in _is_gpu_instance
    self._gpu_info()
  File "/srv/app/servers/spawners.py", line 345, in _gpu_info
    self.gpu_info = resp.json()
  File "/srv/env/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/srv/env/lib/python3.6/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/srv/env/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/srv/env/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by jkp85** [comment]
Fixed in: https://github.com/3Blades/app-backend/pull/484
